/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package passgen

import java.util.Calendar
import kotlin.random.Random

fun randomChar(from: Char, to: Char, except: Char?) : Char {
    var n = Random.nextInt(from.code, to.code).toChar()
    if (n.equals(except))
        n = n + 1
    if (n > to)
        n = from
    return n 
}
fun main() {
    val s = Calendar.getInstance().timeInMillis
    // write your code here    
    // val input = readln().split(" ")
    // var upperC = input[0].toInt()
    // var lowerC = input[1].toInt()
    // var digits = input[2].toInt()
    // val count = input[3].toInt()
    var upperC = 600
    var lowerC = 600
    var digits = 400
    val count = 2000
    // val res = StringBuilder()
    var res = ""
    var q = 0
    val aggr: () -> Int = { upperC + lowerC + digits }
    // checking that total length of characters is not less than password length
    while (aggr() < count) {
        if (aggr() < count && upperC > 0)
            upperC++
        if (aggr() < count && lowerC > 0)
            lowerC++
        if (aggr() < count && digits > 0)
            digits++
    }
    
    if (count > 100)
        println("upper:$upperC lower:$lowerC digits:$digits total:$count")
    while (q++ < count) {
       if (upperC-- > 0)
           res += (randomChar('A', 'Z', res.lastOrNull()))
        if (lowerC-- > 0)
            res += (randomChar('a', 'z', res.lastOrNull()))
        if (digits-- > 0)
            res += (randomChar('0', '9', res.lastOrNull()))
    }
    println(res)
    var e = Calendar.getInstance().timeInMillis
    println("generated in: ${e - s}ms")
}
